---
title: "Math Major"
author: "Matt Rissler"
date: "`r format(Sys.Date())`"
output:
  word_document: 
    fig_width: 7
  html_document: default
  ioslides_presentation:
    keep_md: yes
  beamer_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE)
library(network)
library(sna)
library(ggnetwork)
library(tidyverse)
library(forcats)
library(grid)
```

## The Major

```{r PreReqs, include=FALSE}

n<-network.initialize(17)
network.vertex.names(n)<-c("MAT 150", "MAT 160", "CIT 115", "PHY 223",
                       "MAT 220", "MAT 230", "MAT 250", "MAT 260",
                       "MAT 310", "MAT 420", "MAT 380", "MAT 390",
                       "EDU 353", "MAT 450", "MAT 460", "MAT 490", 
                       "CIT 225")
n %v% "level" <- c("Core", "Core", "Core", "Wing", 
                   "Lower", "Core", "Core", "Core", 
                   "Lower", "Middle", "Middle", "Core",
                   "Wing", "Upper", "Upper", "Core",
                   "Wing")

locations<-matrix(c( 0.75, 0.25,   0.75, 0.75,   0.25, 0.25,   0, 1.25,
                     1, 0.75,   0.3, 0.75,   0.6, 1.25,    1, 1.25,
                     1, 1.75,   0.76, 1.75,    0.31, 2.25,   0.7, 2.25,
                     0.85, 3.25,   0.15, 3.25,    0, 2.25,   0.5, 3.75,
                     0, 1.75), ncol=2, byrow = TRUE)
PreReqs <- data.frame(needed_id= parse_factor(c("MAT 150", "MAT 150", "MAT 150", "MAT 150",
                                   "MAT 160", "MAT 160", "MAT 160", "MAT 160", "MAT 160",
                                   "CIT 115", "CIT 115", "CIT 115",
                                   "MAT 220",
                                   "MAT 230", "MAT 230","MAT 230","MAT 230","MAT 230",
                                   "MAT 250", "MAT 250","MAT 250","MAT 250", "MAT 250",
                                   "MAT 260", "MAT 260", "MAT 260", "MAT 390"),
                                   network.vertex.names(n)), 
                      for_id=    parse_factor(c("MAT 160", "MAT 220", "MAT 230", "MAT 250",
                                   "MAT 310", "MAT 220", "MAT 230", "MAT 260", "PHY 223",
                                   "CIT 225", "MAT 220", "MAT 230",
                                   "MAT 420",
                                   "MAT 380", "MAT 390", "MAT 450", "MAT 460", "MAT 490",
                                   "MAT 390", "MAT 450", "MAT 460", "MAT 490", "MAT 420",
                                   "MAT 390", "MAT 490", "MAT 420", "MAT 490"),
                                   network.vertex.names(n)),
                      type =     c("Pre","Pre","Pre","Pre",
                                   "Pre", "Option", "Option","Pre", "Pre",
                                   "Pre", "Option", "Pre",
                                   "Pre",
                                   "Pre","Pre","Pre","Pre","Pre",
                                   "Pre/Co","Pre/Co","Pre/Co","Pre", "Option",
                                   "Pre", "Pre", "Option", "Pre"),
                      stringsAsFactors = FALSE
                      )

add.edges(n, PreReqs$needed_id,PreReqs$for_id, names.eval =rep("type",dim(PreReqs)[1]), vals.eval= PreReqs$type )
```




```{r plotNetwork, dependson=PreReqs}
net<-ggnetwork(n, layout=locations)
 
g <- rasterGrob(colorRampPalette(c("mediumpurple1", "yellow"))(8), 
                width=unit(1,"npc"), height = unit(1,"npc"), 
                interpolate = FALSE) 
net$type<- parse_factor(net$type, c("Pre", "Option", "Pre/Co"))
ggplot(net, aes(x = x, y = y, xend = xend, yend = yend))+
  annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
  geom_edges(aes(linetype=type),arrow = arrow(length = unit(7, "pt")), 
             curvature=0.1, size=0.75)+
  geom_nodes()+
  geom_segment(aes(x=x,y=y,xend=xend,yend=yend  ),
               data=tibble(x=c(-0.17), y=c(0), xend=c(-0.17), yend=c(1)),
               arrow=arrow(length = unit(7, "pt") ) )+
  annotate("text", x=-.23, y=.5, label="Time") +
  geom_nodelabel(aes(label=vertex.names,fill=level))+
  expand_limits(x=c(-.15,1.05))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        legend.key = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        panel.grid = element_blank()
        ) 
  
```

## The Colors

- Everything in the Core
- At least one Wing
- At least one Upper
- At least two of Middle or Upper
- At least four of Lower, Middle, or Uppper


## Rotation of Classes
Courses that are not listed occur every semester.
```{r When, results="asis"}
class_schedule <- data_frame(Code = c("MAT 150", "MAT 160", "CIT 115", "PHY 223",
                       "MAT 220", "MAT 230", "MAT 250", "MAT 260",
                       "MAT 310", "MAT 380", "MAT 420", "MAT 390",
                       "EDU 353", "MAT 450", "MAT 460", "MAT 490", 
                       "CIT 225"),
                       
                       Title = c("Calc I", "Calc II", "Intro to Programming", "Physics for Mathematicians",
                       "Prob/Stats", "Discrete Math", "Linear Algebra", "Multivariable Calc",
                       "ODEs", "Modern Geometry", "Numerical Analysis", "Seminar",
                       "Math Methods", "Algebra", "Real Analysis", "Capstone",
                       "Data Structures and Algorithms"), 
                       
                       Semester = c("Every", "Every","Every","Fall",
                       "Spring", "Spring", "Fall", "Every",
                       "Spring", "Odd Falls", "Odd Springs", "Every",
                       "Even Falls", "Even Falls", "Odd Falls", "Spring",
                       "Every")
                       )
                       
class_schedule %>% filter(Semester != "Every") %>% slice(1:5) %>%  knitr::kable()

```


## Rotation of Classes

```{r When2, results="asis", dependson="When"}
class_schedule %>% filter(Semester != "Every") %>% slice(6:n()) %>%  knitr::kable()

```